# Dependencies
markdown: kramdown
highlighter: rouge

title: Phan Nguyen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

permalink: pretty
tagline: 
description: A human learner
url: http://pab-nguyen.github.io
baseurl: "/"
author:
  name: Mark Otto
  url: https://twitter.com/mdo
paginate_path: "/portfolio/page:num"
version: 2.1.0
github:
  repo: https://github.com/poole/hyde
